##### From Allowing you to pull dependenices from other images  ##################################

FROM ubuntu:16.04

#############    RUN from within the container when it's first Created     #######################

# Install dependencies
RUN apt-get update
RUN apt-get -y install apache2

# Install apache and write hello world message
RUN echo 'Hello World!' > /var/www/html/index.html

# Configure apache
RUN echo '. /etc/apache2/envvars' > /root/run_apache.sh
RUN echo 'mkdir -p /var/run/apache2' >> /root/run_apache.sh
RUN echo 'mkdir -p /var/lock/apache2' >> /root/run_apache.sh
RUN echo '/usr/sbin/apache2 -D FOREGROUND' >> /root/run_apache.sh
RUN chmod 755 /root/run_apache.sh

######################################################################################################
########  ENV Sets an Environment Variable Available within the Container usefull for setting  variables that software needs to be run
#####################################################################################################
########  VOLUME defines a path in the container that docker exposes to the host system and mapped using the -v Argument when running a container
######################################################################################################
#######   WORKDIR Changes the active Directory of the container to a specifed location ,in case you need to run commands from or in a particular location
#####################################################################################################
####### CMD runs the software that the container is designed to run the format CMD [executable1] [executable2]
####### CMD used for interactive shell such as python ex: spark-shell --master yarn   Redefines as CMD [Spark-shell] [--master] [yarn]
##################################################################################################


EXPOSE 80

CMD /root/run_apache.sh